### PR TITLE
🐍 Write a script for generating a CSV of speakers and twitter handles

### PR DESCRIPTION
**Pull request by drewbrew**
This makes the comms team's life much easier.

The link to the generated data is in the comms channel in slack.

### CODE REVIEW

**Comment by jefftriplett** [comment]
🤔  I thought we already had this.

**Comment by drewbrew** [comment]
I thought so too but couldn't find it. I ended up writing it from scratch.

**Comment by jefftriplett** [comment]
I must have been thinking of https://2022.djangocon.us/speaking/twitter/

I could go either way on the script if it's useful for other things. I'm going to fix the layout either way since that's useful for quick copy and paste later (once we have youtube too)

**Comment by drewbrew** [comment]
If it's useful to Carol, we'll keep it for next year. Otherwise, I'm good with scrapping it.

**Review by jefftriplett — APPROVED** [review]
approving in case you want to merge it.

**Comment by drewbrew** [comment]
Carol is using it to track when she's tweeted about talks, so I'm going to merge this.

**Pull request merged**
