### PR TITLE
Initial bio and image for Timothy Allen.

### LINKED ISSUE #208: Create bio for myself
**Expected behavior:**

**Actual behavior:**

**Steps to repeat behavior:**

-
-

### PR DESCRIPTION
**Pull request by FlipperPA**
Closes #208.

Changes proposed in this PR:
Add bio for Timothy Allen.

### CODE REVIEW

**Comment by drewbrew** [comment]
Looks good so far! Do you want me to merge this now or wait for your schedule update?

**Comment by FlipperPA** [comment]
@drewbrew Let me get it wrapped up, I still need to add a description for the talk. I'll have it done in a few hours after dinner! :)

**Comment by drewbrew** [comment]
Good by me!

**Comment by FlipperPA** [comment]
@drewbrew I think this should be good to go! Feel free to make any edits, fixes or changes as you see fit, and thank you!

**Review by drewbrew — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
