### PR TITLE
Update speaker info

### PR DESCRIPTION
**Pull request by glasnt**
Changes proposed in this PR:

- Update speaker pronouns, website, github

I want to also update my talk difficulty level, but I don't know what to choose. 

I want to say "Beginner" because I would hope that my presentation would be accessible for beginners, but the problem my talk is based around is "Advanced" as it gets complex as. I don't want to other potential audience members who think my talk isn't for them.

### CODE REVIEW

**Review by logankilpatrick — APPROVED** [review]

**Comment by logankilpatrick** [comment]
Hey @glasnt! Maybe you can say that in the talk details so that folks know the talk will be "beginner" level but the actual concept is more of a "advanced" concept?

**Comment by glasnt** [comment]
Good suggestion @logankilpatrick, but then I'm not sure if the talk itself will be seen as non-technical ><

**Comment by logankilpatrick** [comment]
Reading the abstract for the talk my impression is that it is definitely a very cool technical topic! But interested to see if others have different thoughts: https://2022.djangocon.us/talks/scheming-with-csrf-when-platforms-manage/

**Review by drewbrew — APPROVED** [review]
What about "All" for the difficulty?

**Comment by glasnt** [comment]
@drewbrew "All" wasn't listed in the speaker email, but I can see it being used for keynotes etc. I'll update my PR and add a note in the abstract about difficultly for clarity. Happy for the level to be changed based on other talks as we go. I want to prioritise audience information as to what they should expect.

**Review by drewbrew — APPROVED** [review]
I like it!

**Pull request merged**
