### PR TITLE
📝 Make updates to ticket page

### PR DESCRIPTION
**Pull request by drewbrew**
1. Add Catherine's explanation for why there aren't any early bird tickets this year.
2. Add a note about converting in-person to online tickets.

### CODE REVIEW

**Review by jefftriplett — APPROVED** [review]

**Comment by logankilpatrick** [comment]
Does this mean if someone downgrades to online ticket, they still pay a 10% fee? Imo we should waive the fee if they downgrade to online

**Comment by cholmes5** [comment]
I can change it to that in ti.to if people want (and I’m sure it would still need to be changed elsewhere too). If we do that, when it gets closer to the conference, it is much cheaper to convert to online than to cancel, which seems strange to me (for corporate, would refund 400 for normal refund, would refund 500 if converting to an online ticket. For individual, it’s 300 vs 450). So, that’s the reason I proposed what I did, and no one objected when I put it in whatever channel I was in, so I did it.


But, we can rethink the whole thing. I don’t mind something that could potentially help get people committed to come. Ticket sales have been low so far, so maybe switching to a policy of exchange to online and refund the remainder would encourage more people to commit? I certainly don’t mind trying something new. I can write something up to highlight what the policy used to be and how converting to online is better.

(I can also just drop the 10% period so it’s a full refund until Oct 1.)

Catherine

**Comment by jefftriplett** [comment]
Re: 10% - I think our goal with 30 days is because that's when we have to turn in our final head count for food and beverages. So if we can't fill the seat, we potentially lose more than the online ticket covers. If they cancel due to COVID then I'm not going to argue that we have a policy that penalizes anyone for not attending due to a medical reason.

**Comment by logankilpatrick** [comment]
Yeah that's fair, I missed the tiered cancelation fees. I think this makes sense in general since we have sunk costs.

**Pull request merged**
